name: Update Shenzhen Weather

on:
  # 手动触发按钮
  workflow_dispatch:
  # 每天北京时间 08:00 & 20:00 运行（GitHub 使用 UTC，需要换算）
  schedule:
    - cron: "0 0 * * *"   # UTC 00:00 -> 北京时间 08:00
    - cron: "0 12 * * *"  # UTC 12:00 -> 北京时间 20:00

permissions:
  contents: write   # 允许提交回仓库

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run script
        run: |
          python fetch_weather.py

      - name: Commit & push if changed
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: update weather in README [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
